[package]
name = "wgsl_modules_loader"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "wgsl_modules_loader"

[dependencies]
regex-lite = { version = "0.1" }
naga = { workspace = true }
anyhow = { workspace = true }